# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Geordie Hess
title: Salesforce Engineering Manager
email: geordiehess44@gmail.com
# website: https://geordiehess44.github.io/resume2026

# Social links
twitter_username: geordiehess
#github_username:  geordiehess44
# dribbble_username: jekyll
facebook_username: geordiehess
# flickr_username: jekyll
instagram_username: geordie.hess
linkedin_username: george-hess-1461206
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Driven, productive, and effective engineering manager and Salesforce.com professional with 20 years of experience, 
  ranging from start-ups to enterprise-level organizations.  I have been managing and developing applications 
  and services in the telecom, daily-deals, and fintech industries, serving across all business functions including, but
  not limited to sales, sales operations, customer service, finance, marketing, and human resources.  I thrive on 
  cross-functional collaboration with product management, business stakeholders, and design teams with an emphasis 
  on user-centered products.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Professional Skills
more_content: | # this will include new lines to allow paragraphs
        <ul>  <li><b>Salesforce.com Technologies</b>: Apex Classes, Test Classes, SOQL, SOSL, Visual Force, Lightning pages (Pages, Component & Controllers), ETL, Triggers, Web services, Sandbox development and Testing
        <li><b>Languages:</b> Java, Ruby, Apex</li>
        <li><b>Web Technologies:</b> XML, HTML, CSS, JavaScript</li>
        <li><b>Version Control Tools:</b> GitHub</li>
        <li><b>Web Services:</b> SOAP, WSDL, JSON, REST</li>
        <li><b>Databases:</b> MySQL, PostgreSQL</li>
        <li><b>Public Speaking:</b> Presented at numerous Salesforce.com <a href="https://www.salesforce.com/dreamforce/" target="_blank">Dreamforce</a> events</li>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
